In [3]:
import pandas as pd

df=pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ', '_')
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [12]:
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [14]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [16]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [18]:
df=df.drop('promo_code_used',axis=1)

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [ ]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\Users\rahul\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\Users\rahul\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\Users\rahul\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\rahul\AppData\Roaming\Python\Python311\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine

In [ ]:
username="postgres"
password="your_password"  # Replace with your actual password
host="localhost"
port="5432"
database="customer_behavior"
engine=create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

table_name="customer"
df.to_sql(table_name,engine,if_exists='replace',index=False)

print(f"Data inserted into the {table_name} table in the {database} database.")

Data inserted into the customer table in the customer_behavior database.

In [ ]:
query = "SELECT * FROM customer LIMIT 5"

pd.read_sql(query, engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [ ]:
#total revenue generated by male and female customers
q1 = '''
select gender,
sum("purchase_amount_(usd)") as revenue
from customer
group by gender
'''

pd.read_sql(q1, engine)

   gender   revenue
0  Female   75191.0
1    Male  157890.0

In [ ]:
#customers with discount whose purchase is closest to average purchase
q2 = '''
select 
    customer_id,
    "purchase_amount_(usd)"
from customer
where discount_applied='Yes'
order by abs(
    "purchase_amount_(usd)" - 
    (select avg("purchase_amount_(usd)") from customer)
)
'''

pd.read_sql(q2, engine)

      customer_id  purchase_amount_(usd)
0            1434                     60
1             858                     60
2             677                     60
3             635                     60
4             304                     60
...           ...                    ...
1672          244                    100
1673          616                    100
1674         1457                    100
1675          456                    100
1676         1209                    100

[1677 rows x 2 columns]

In [29]:
#top 5 products with highest average review rating
q3 = '''
select 
    item_purchased,
    round(avg(review_rating)::numeric, 2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5
'''

pd.read_sql(q3, engine)

  item_purchased  Average Product Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.78

In [ ]:
#average purchase amount for each shipping type
q4 = '''
select 
    shipping_type,
    round(avg("purchase_amount_(usd)")::numeric, 2) as average_purchase
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
'''

pd.read_sql(q4, engine)

  shipping_type  average_purchase
0      Standard             58.46
1       Express             60.48

In [ ]:
#total revenue and average spend for each subscription status
q5 = '''
select 
    subscription_status,
    count(customer_id) as total_customers,
    round(avg("purchase_amount_(usd)")::numeric, 2) as avg_spend,
    round(sum("purchase_amount_(usd)")::numeric, 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc
'''

pd.read_sql(q5, engine)

  subscription_status  total_customers  avg_spend  total_revenue
0                 Yes             1053      59.49        62645.0
1                  No             2847      59.87       170436.0

In [ ]:
#top 5 products with highest discount rate
q6 = '''
select 
    item_purchased,
    round(
        sum(
            case 
                when discount_applied='Yes' then 1 
                else 0 
            end
        ) * 100.0 / count(*), 
        2
    ) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5
'''

pd.read_sql(q6, engine)

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [ ]:
#segment customers based on their previous purchases into three categories: New, Returning, and Loyal. Then, count the number of customers in each segment.
q7 = '''
with customer_type as (
    select 
        customer_id,
        previous_purchases,
        case
            when previous_purchases = 1 then 'New'
            when previous_purchases between 2 and 10 then 'Returning'
            else 'Loyal'
        end as customer_segment
    from customer
)

select 
    customer_segment,
    count(*) as "Number of Customers"
from customer_type
group by customer_segment
'''

pd.read_sql(q7, engine)

  customer_segment  Number of Customers
0            Loyal                 3116
1              New                   83
2        Returning                  701

In [ ]:
#top 3 most purchased items in each category
q8 = '''
with item_counts as (
    select
        category,
        item_purchased,
        count(customer_id) as total_orders,
        row_number() over(
            partition by category
            order by count(customer_id) desc
        ) as item_rank
    from customer
    group by category, item_purchased
)

select
    item_rank,
    category,
    item_purchased,
    total_orders
from item_counts
where item_rank <= 3
'''

pd.read_sql(q8, engine)

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing         Blouse           171
4           2     Clothing          Pants           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [35]:
#are customers with more than 5 previous purchases more likely to be subscribed to a subscription plan?
q9 = '''
select
    subscription_status,
    count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
'''

pd.read_sql(q9, engine)

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [36]:
#revenue contribution from different age groups
q10 = '''
select
    age_group,
    sum("purchase_amount_(usd)") as total_revenue
from customer
group by age_group
order by total_revenue desc
'''

pd.read_sql(q10, engine)

     age_group  total_revenue
0  Young Adult        62143.0
1  Middle-aged        59197.0
2        Adult        55978.0
3       Senior        55763.0